import Circle from './circle'
import BatteryNode from './batteryNode'
import Energy from './energy'
import NimationObject from './nimationObject'
import Node from './node'
import Packet from './packet'
import Scene from './scene'
import '../../style/node_style.css'

export const RED = '#ff5555'
export const ORANGE = '#F39C12'
export const BLUEVIOLET = '#5533ff'
export const GREEN = '#55ff33'
export const BLUE = '#1144ff'
export const PURPLE = '#8E44AD'
export const YELLOW = '#F4D03F'
export const SKYBLUE = '#5DADE2'
export const WHITE = '#FDFEFE'
